# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: tiana.bettinson@gmail.com
author_name: tbetti
contract_name: backend
deployment_language: python
preset_name: production
project_name: carbon-aquarian-contracts

